/* Materi & bank soal pembagian. Tambah soal di sini. */
/* ---------- Bank soal ---------- */
const D=(total,groups,emoji,noun,names,q,ex,topic)=>({t:'dist',total,groups,emoji,noun,names,q,ex,topic,v:[total,groups,emoji]});
const N=(q,a,hint,o={})=>Object.assign({t:'num',q,a,hint},o);
const C=(q,opts,a,hint,o={})=>Object.assign({t:'mc',q,opts,a,hint},o);
const R=(n,g,hint)=>({t:'rem',q:`${n} ÷ ${g} = ... sisa ...`,n,g,a:[Math.floor(n/g),n%g],hint,v:n<=60?[n,g]:null,topic:'sisa'});
const dv=(n,d,hint)=>N(`${n} ÷ ${d} = ...`,n/d,hint||`Coba gunakan perkalian. Berapa × ${d} yang hasilnya ${n}?`,{v:n<=48?[n,d]:null,topic:'bil'});
function pre(){return[D(12,3,'🍎','apel',['Anak 1','Anak 2','Anak 3'],'Ada 12 apel yang akan dibagikan kepada 3 anak secara adil. Berapa apel yang diterima setiap anak?',''),N('Ada 15 kelereng dibagi ke 3 kelompok sama banyak. Berapa kelereng tiap kelompok?',5,'',{}),N('20 ÷ 4 = ...',5,'',{}),N('Jika 4 × 6 = 24, maka 24 ÷ 4 = ...',6,'',{}),R(17,5,'')]}
function m1(){return[D(8,2,'🍊','jeruk',['Anak A','Anak B'],'Ibu mempunyai 8 jeruk. Ibu ingin membagikannya kepada 2 anak secara adil.','8 ÷ 2 = 4. Setiap anak mendapatkan 4 jeruk.','konsep'),D(12,3,'🍎','apel',['Kotak 1','Kotak 2','Kotak 3'],'Misi 1: Ada 12 apel. Bagikan kepada 3 anak secara adil.','12 ÷ 3 = 4. Setiap anak mendapatkan 4 apel.','konsep')]}
function m2(){return[D(15,3,'🔵','kelereng',['Kelompok A','Kelompok B','Kelompok C'],'Ada 15 kelereng. Buatlah 3 kelompok dengan jumlah kelereng yang sama.','15 ÷ 3 = 5. Setiap kelompok berisi 5 kelereng.','konsep'),D(16,4,'🍬','permen',['Toples 1','Toples 2','Toples 3','Toples 4'],'Ada 16 permen. Masukkan ke 4 toples dengan jumlah sama banyak.','16 ÷ 4 = 4. Setiap toples berisi 4 permen.','konsep'),rd(),C('Apa yang terjadi jika satu kelompok memiliki lebih banyak kelereng daripada kelompok lain?',['Semua kelompok tetap adil.','Kelompok tidak sama banyak.','Tidak ada perubahan.'],1,'Ingat: membagi berarti membuat kelompok yang sama banyak.',{topic:'konsep'})]}
function m3(){const p='20 benda ÷ 4 kelompok = 5 benda setiap kelompok\n20 ÷ 4 = 5';const o=['Jumlah seluruh benda.','Jumlah kelompok.','Jumlah benda setiap kelompok.'];return[C('Apa arti angka 20?',o,0,'Ada 20 benda semuanya sebelum dibagi.',{pre:p,topic:'konsep'}),C('Apa arti angka 4?',o,1,'Benda dibagi ke berapa kelompok?',{pre:p,topic:'konsep'}),C('Apa arti angka 5?',o,2,'Setelah dibagi, tiap kelompok berisi berapa?',{pre:p,topic:'konsep'}),C('Bilangan yang dibagi adalah ...',['20','4','5'],0,'Bilangan yang dibagi adalah jumlah seluruh benda.',{pre:p,topic:'konsep',ex:'Bilangan yang dibagi: 20 · Pembagi: 4 · Hasil bagi: 5.'}),C('Pembagi adalah ...',['20','4','5'],1,'Pembagi adalah jumlah kelompok.',{pre:p,topic:'konsep'})]}
function m4base(){return[N('Jika 4 kelompok masing-masing berisi 5 benda, berapa jumlah seluruh benda?',20,'Hitung 4 × 5.',{pre:'4 × 5 = ?',topic:'kali'}),N('4 × 5 = 20, maka 20 ÷ 4 = ...',5,'Berapa × 4 yang hasilnya 20?',{v:[20,4],topic:'kali'}),N('4 × 5 = 20, maka 20 ÷ 5 = ...',4,'Berapa × 5 yang hasilnya 20?',{v:[20,5],topic:'kali'}),N('6 × 7 = 42, maka 42 ÷ 6 = ...',7,'Gunakan fakta perkalian 6 × 7.',{topic:'kali'}),N('6 × 7 = 42, maka 42 ÷ 7 = ...',6,'Gunakan fakta perkalian 6 × 7.',{topic:'kali',ex:'💡 Perkalian dan pembagian saling berhubungan. Jika kamu tahu fakta perkalian, kamu bisa memakainya untuk menyelesaikan pembagian.'})]}

function m6base(){const w=(a,b,c,d)=>`   ${a}\n6 )144\n   ${b}\n   --\n   ${c}${d?'\n   '+d:''}`;return[C('Berapa kali 6 dapat masuk ke angka 14 tanpa melebihi 14?',['1','2','3'],1,'6 × 2 = 12 dan 6 × 3 = 18 (terlalu besar).',{pre:'  ?\n6 )144',topic:'bers'}),N('Sudah ada 2 × 6 = 12. Berapa 14 dikurangi 12?',2,'14 − 12 = ...',{pre:'  2\n6 )144\n  12\n  --\n   ?',topic:'bers'}),N('Angka 4 diturunkan. Sekarang bilangannya menjadi ...?',24,'Sisa 2 dan angka 4 digabung.',{pre:'  2\n6 )144\n  12\n  --\n   2↓\n   ?',topic:'bers'}),N('Berapa kali 6 dapat masuk ke 24?',4,'Berapa × 6 yang hasilnya 24?',{topic:'bers'}),N('Hasil akhir 144 ÷ 6 = ...',24,'Gabungkan angka di atas: 2 lalu 4.',{pre:' 24\n6 )144\n  12\n  --\n   24\n   24\n   --\n    0',topic:'bers',ex:'144 ÷ 6 = 24 🎉'}),N('Sekarang coba sendiri: 156 ÷ 6 = ...',26,'Mulai dari 15: berapa kali 6 masuk ke 15?',{topic:'bers'})]}
function m7base(){return[R(17,5,'Setiap kotak diisi sama banyak dulu. Sisanya yang belum terbagi rata ditulis sebagai sisa.'),R(23,4,'Cari perkalian 4 terdekat yang tidak melebihi 23.'),R(47,6,'6 × 7 = 42. Berapa sisanya dari 47?'),C('Apakah 20 ÷ 4 memiliki sisa?',['Ya, ada sisa.','Tidak, habis terbagi.'],1,'4 × 5 = 20 tepat.',{topic:'sisa'})]}

function m10(){const F=(q,o)=>C(q,o,0,'',{free:1,ex:'Terima kasih sudah merefleksi! 🌟'});return[C('Apa arti 36 ÷ 6 = 6?',['36 benda dibagi sama rata ke 6 kelompok, tiap kelompok berisi 6.','36 benda ditambah 6 benda.','6 benda dikalikan 36 kelompok.'],0,'Ingat arti pembagian: membuat kelompok sama banyak.',{topic:'konsep'}),N('Jika 7 × 8 = 56, maka 56 ÷ 7 = ...',8,'Gunakan fakta perkalian.',{topic:'kali'}),N('384 ÷ 8 = ...',48,'Mulai dari 38: berapa kali 8 masuk ke 38?',{topic:'bers'}),R(47,6,'6 × 7 = 42. Berapa sisanya?'),N('325 buku dibagikan kepada 5 kelas sama rata. Berapa buku tiap kelas?',65,'325 ÷ 5 dengan pembagian bersusun.',{topic:'cer'}),...mix(),F('Hari ini saya belajar bahwa pembagian adalah ...',['Membagi menjadi kelompok yang sama banyak.','Menjumlahkan semua benda.','Mengurangi tanpa tujuan.']),F('Bagian mana yang paling kamu sukai?',['Membagi benda.','Permainan.','Pembagian bersusun.','Soal cerita.'])]}


/* ---------- Generator soal acak (tingkat bertahap) ---------- */
const rnd=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
const DE=[['🍎','apel'],['🍊','jeruk'],['🍪','kue'],['🔵','kelereng'],['⭐','bintang'],['🍬','permen']];
function rd(){const g=rnd(2,5),k=rnd(2,5),[e,n]=pick(DE);return D(g*k,g,e,n,Array.from({length:g},(_,i)=>'Kotak '+(i+1)),`Ada ${g*k} ${n}. Bagikan ke ${g} kotak dengan jumlah sama banyak.`,`${g*k} ÷ ${g} = ${k}. Setiap kotak berisi ${k} ${n}.`,'konsep')}
function ff(){const a=rnd(3,9),b=rnd(3,9),p=a*b;return pick([()=>N(`${a} × ${b} = ${p}, maka ${p} ÷ ${a} = ...`,b,`Berapa × ${a} yang hasilnya ${p}?`,{v:p<=48?[p,a]:null,topic:'kali'}),()=>N(`${a} × ${b} = ${p}, maka ${p} ÷ ${b} = ...`,a,`Berapa × ${b} yang hasilnya ${p}?`,{v:p<=48?[p,b]:null,topic:'kali'}),()=>N(`${a} × ... = ${p}`,b,`Cari bilangan yang jika dikali ${a} hasilnya ${p}.`,{topic:'kali'})])()}
function m4(){return m4base().concat([ff(),ff(),ff()])}
function m5(){const t=(lo,hi,n,dlo,dhi)=>Array.from({length:n},()=>{const d=rnd(dlo,dhi),a=rnd(lo,hi);return dv(d*a,d,a>12?'Gunakan perkalian atau pembagian bersusun.':'')});
return [...t(2,9,3,2,9),...t(6,12,3,3,9),...t(13,40,3,3,9)]}
function ind(lo,hi){const d=rnd(3,9),a=rnd(lo,hi),n=d*a,s=String(n),h=+s[0]>=d?s[0]:s.slice(0,2);return N(`Hitung dengan pembagian bersusun: ${n} ÷ ${d} = ...`,a,`Mulai dari angka depan. Berapa kali ${d} masuk ke ${h}?`,{topic:'bers',pre:`  ?\n${d} )${n}`})}
function m6(){return m6base().concat([ind(12,30),ind(31,99),ind(101,199)])}
function rr(){const d=rnd(3,9),q=rnd(3,9),r=rnd(1,d-1),n=d*q+r;return R(n,d,`Cari perkalian ${d} terdekat yang tidak melebihi ${n}. Selisihnya adalah sisa.`)}
function m7(){return m7base().concat([rr(),rr(),rr()])}
const SX=[['Bu Sari membuat','kue','kotak'],['Petani memanen','jeruk','keranjang'],['Pak Amir memiliki','pensil','kelas'],['Toko memiliki','permen','toples'],['Pak Dedi menanam','bibit cabai','baris']];
function st(tier,rem){const [s,it,u]=pick(SX),g=rnd(3,9),a=tier===0?rnd(4,12):tier===1?rnd(13,40):rnd(41,99),r=rem?rnd(1,g-1):0,n=g*a+r,v=n<=60?[n,g]:null;
const q=`${s} ${n} ${it}, dimasukkan ke ${g} ${u} dengan jumlah sama banyak. `;
return rem?Object.assign(R(n,g,'Bagi dulu, sisanya adalah benda yang belum terbagi rata.'),{q:q+`Berapa isi tiap ${u} dan berapa sisanya?`,topic:'cer',v}):N(q+`Berapa ${it} di setiap ${u}?`,a,'Ceritanya tentang membagi sama rata, jadi gunakan pembagian.',{topic:'cer',v})}
function m8(){return[C('Perpustakaan memiliki 240 buku, dibagikan sama rata kepada 8 kelas. Operasi apa yang tepat?',['Dijumlahkan','Dikurangi','Dibagikan sama rata (dibagi)'],2,'Mari kita baca kembali ceritanya. Apakah benda-benda tersebut akan digabungkan, dikurangi, atau dibagikan sama rata?',{topic:'cer'}),st(0),st(0),st(1),st(1),st(2),st(1,1)]}
function mix(){return[dv(...(()=>{const d=rnd(3,9);return[d*rnd(13,40),d]})()),ind(31,99),st(1,1)]}
